name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: pypi

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip build

    - name: Clean old builds
      run: |
        rm -rf build dist *.egg-info

    - name: Build package
      run: python -m build

    - name: Publish to PyPI (Trusted Publisher)
      uses: pypa/gh-action-pypi-publish@release/v1
